name: build

on:
  push:
    branches: master

jobs:
  build-mirrorbot-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the mirrorbot Docker image
      run: |
        docker build . --tag ghcr.io/philipinho/mirrorbot:latest
        docker push ghcr.io/philipinho/mirrorbot:latest
